name: PokeVault
options:
  minimumXcodeGenVersion: 2.38.0
configs:
  Debug: debug
  Release: release
targets:
  PokeVault:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taconetwork.pokevault
        DEVELOPMENT_TEAM: ""
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
    sources:
      - path: PokeVault/Sources
      - path: PokeVault/Resources
    info:
      path: PokeVault/Resources/Info.plist
      properties:
        CFBundleDisplayName: PokeVault
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: false
        NSCameraUsageDescription: Allow camera access to scan Pokémon cards.
        NSPhotoLibraryUsageDescription: Allow photo library access to select Pokémon card images.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains:
            "172.22.22.51":
              NSExceptionAllowsInsecureHTTPLoads: true
